### ISSUE TITLE
Configure the Travis job

### ISSUE THREAD

**Issue by PixnBits** [claudetech/node-cdnify#3]
Sorry if this is already done, but from what I can tell it looks like the previous PRs (#1, #2) didn't get automatically built by Travis. Could we get Travis' signoff on builds before a patch version update? (Chasing down CSSwhat messages in my npm install log)

**Comment by PixnBits** [comment]
I haven't done this for any projects yet so I don't have any pointers, but I'm willing to help if desired.

**Comment by danhper** [comment]
Travis build seems to be running properly, but I'm not sure why the pull request was not built.
Travis is set to build both pushes and pull requests.
https://travis-ci.org/claudetech/node-cdnify
Let's close this for now and reopen if it does not build for the next pull request.

**Comment by PixnBits** [comment]
Awesome, thanks!
